#!/usr/bin/env python3

import argparse
import json
import random
from pathlib import Path


MATRIX_N = 4
DATA_W = 8
ACC_W = 32
MATRIX_ELEMS = MATRIX_N * MATRIX_N


def int8(value):
    value &= 0xFF
    return value - 0x100 if value & 0x80 else value


def flatten(matrix):
    return [matrix[row][col] for row in range(MATRIX_N) for col in range(MATRIX_N)]


def unflatten(values):
    return [values[row * MATRIX_N:(row + 1) * MATRIX_N] for row in range(MATRIX_N)]


def matmul4(a, b):
    if len(a) == MATRIX_ELEMS:
        a = unflatten(a)
    if len(b) == MATRIX_ELEMS:
        b = unflatten(b)

    c = [[0 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    for row in range(MATRIX_N):
        for col in range(MATRIX_N):
            acc = 0
            for k in range(MATRIX_N):
                acc += int8(a[row][k]) * int8(b[k][col])
            c[row][col] = acc
    return c


def print_matrix(name, matrix):
    print(f"{name}:")
    for row in matrix:
        print("  " + " ".join(f"{value:6d}" for value in row))


def fixed_test_vectors():
    identity = [[1 if row == col else 0 for col in range(MATRIX_N)] for row in range(MATRIX_N)]
    zero = [[0 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    ones = [[1 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    seq = [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
    ]
    mixed_a = [
        [1, -2, 3, -4],
        [5, 6, -7, 8],
        [-9, 10, 11, -12],
        [13, -14, 15, 16],
    ]
    mixed_b = [
        [-1, 2, -3, 4],
        [5, -6, 7, -8],
        [9, 10, -11, 12],
        [-13, 14, 15, -16],
    ]
    max_positive = [[127 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    min_negative = [[-128 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    alternating = unflatten([127 if idx % 2 == 0 else -128 for idx in range(MATRIX_ELEMS)])
    sparse_a = [[0 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    sparse_b = [[0 for _ in range(MATRIX_N)] for _ in range(MATRIX_N)]
    sparse_a[1][2] = -128
    sparse_b[2][3] = 127

    return [
        ("identity", identity, seq),
        ("all_zeros", zero, [[col - 8 + row * MATRIX_N for col in range(MATRIX_N)] for row in range(MATRIX_N)]),
        ("all_ones", ones, ones),
        ("mixed_signed", mixed_a, mixed_b),
        ("max_positive", max_positive, max_positive),
        ("min_negative_times_positive", min_negative, max_positive),
        ("alternating_extremes", alternating, alternating),
        ("sparse_single_nonzero", sparse_a, sparse_b),
    ]


def generated_tests(num_tests, seed):
    rng = random.Random(seed)
    tests = []
    for idx in range(num_tests):
        a = [rng.randint(-128, 127) for _ in range(MATRIX_ELEMS)]
        b = [rng.randint(-128, 127) for _ in range(MATRIX_ELEMS)]
        c = flatten(matmul4(a, b))
        tests.append({
            "name": f"random_seed_{seed}_{idx}",
            "A": a,
            "B": b,
            "C_expected": c,
        })
    return tests


def write_json(path, tests):
    data = {
        "matrix_n": MATRIX_N,
        "data_width": DATA_W,
        "acc_width": ACC_W,
        "tests": tests,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def write_svh(path, tests):
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by model/golden_matmul.py. Regenerate with make vectors.",
        "`ifndef TINYNPU_GENERATED_MATMUL_TESTS_SVH",
        "`define TINYNPU_GENERATED_MATMUL_TESTS_SVH",
        "",
        f"localparam int NUM_GENERATED_TESTS = {len(tests)};",
        "",
        "task automatic load_generated_test(",
        "  input int test_idx,",
        "  output logic [DATA_W*MATRIX_ELEMS-1:0] a_values,",
        "  output logic [DATA_W*MATRIX_ELEMS-1:0] b_values,",
        "  output logic [C_FLAT_W-1:0] expected",
        ");",
        "  begin",
        "    a_values = '0;",
        "    b_values = '0;",
        "    expected = '0;",
        "    case (test_idx)",
    ]

    for idx, test in enumerate(tests):
        lines.append(f"      {idx}: begin")
        for elem_idx, value in enumerate(test["A"]):
            lines.append(f"        set_i8(a_values, {elem_idx}, {value});")
        for elem_idx, value in enumerate(test["B"]):
            lines.append(f"        set_i8(b_values, {elem_idx}, {value});")
        for elem_idx, value in enumerate(test["C_expected"]):
            lines.append(f"        set_i32(expected, {elem_idx}, {value});")
        lines.append("      end")

    lines.extend([
        "      default: begin",
        "      end",
        "    endcase",
        "  end",
        "endtask",
        "",
        "`endif",
        "",
    ])
    path.write_text("\n".join(lines))


def print_fixed():
    for name, a, b in fixed_test_vectors():
        print(f"\n{name}")
        print_matrix("A", a)
        print_matrix("B", b)
        print_matrix("C", matmul4(a, b))


def parse_args():
    parser = argparse.ArgumentParser(description="tinyNPU 4x4 int8 matmul golden model")
    parser.add_argument("--print-fixed", action="store_true", help="print directed fixed test vectors")
    parser.add_argument("--generate-json", action="store_true", help="write generated JSON vectors")
    parser.add_argument("--generate-svh", action="store_true", help="write generated SystemVerilog include vectors")
    parser.add_argument("--num-tests", type=int, default=50, help="number of generated random tests")
    parser.add_argument("--seed", type=int, default=1, help="deterministic random seed")
    parser.add_argument("--out", default="tests/test_vectors/generated_matmul_tests.json", help="JSON output path")
    parser.add_argument("--svh-out", default="tests/test_vectors/generated_matmul_tests.svh", help="SVH output path")
    return parser.parse_args()


def main():
    args = parse_args()

    if not args.print_fixed and not args.generate_json and not args.generate_svh:
        args.print_fixed = True

    if args.print_fixed:
        print_fixed()

    if args.generate_json or args.generate_svh:
        tests = generated_tests(args.num_tests, args.seed)
        if args.generate_json:
            write_json(Path(args.out), tests)
            print(f"Wrote {len(tests)} JSON tests to {args.out}")
        if args.generate_svh:
            write_svh(Path(args.svh_out), tests)
            print(f"Wrote {len(tests)} SVH tests to {args.svh_out}")


if __name__ == "__main__":
    main()
